name: Download File

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download file
      run: |
        wget https://github.com/Lintao-Zeng/DownloadFile/raw/main/download.py
        ls
        pip install tqdm
        python download.py
        
